FROM golang:1.20-alpine3.18 AS builder

RUN apk --no-cache add make

COPY . /go/src/github.com/tozd/sops
WORKDIR /go/src/github.com/tozd/sops

RUN CGO_ENABLED=1 make install


FROM alpine:3.18

RUN apk --no-cache add \
  vim ca-certificates
ENV EDITOR vim
COPY --from=builder /go/bin/sops /usr/local/bin/sops
ENTRYPOINT ["/usr/local/bin/sops"]
